site_name: BubbleID_My
nav:
  - Accueil: index.md
  - Installation: installation.md
  - API: api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["Customizable"]

markdown_extensions:
  - mkdocstrings
  - admonition
  - toc:
      permalink: true